before:
  hooks:
    - go mod tidy

builds:
  - id: curlor
    main: ./cmd/curlor/main.go
    binary: curlor
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux

archives:
  - builds:
      - curlor
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'update workflows'